=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 1.10.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Harbor1Client::DigitalSignature
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DigitalSignature' do
  before do
    # run before each test
    @instance = Harbor1Client::DigitalSignature.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DigitalSignature' do
    it 'should create an instance of DigitalSignature' do
      expect(@instance).to be_instance_of(Harbor1Client::DigitalSignature)
    end
  end
  describe 'test attribute "signed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "prov_file"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
