=begin
#Harbor API

#These APIs provide services for manipulating Harbor project.

OpenAPI spec version: 1.10.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.22

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Harbor1Client::RoleParam
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RoleParam' do
  before do
    # run before each test
    @instance = Harbor1Client::RoleParam.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RoleParam' do
    it 'should create an instance of RoleParam' do
      expect(@instance).to be_instance_of(Harbor1Client::RoleParam)
    end
  end
  describe 'test attribute "roles"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
